### ISSUE TITLE
'../Embeds/sdp_correct_embeds.pkl'

### ISSUE THREAD

**Issue by Yueqing-Sun** [LiangsLi/LSTM_Biaffine_Dependency_Parser_PyTorch#1]
请问怎么得到'../Embeds/sdp_correct_embeds.pkl'文件？

**Comment by LiangsLi** [comment]
> 请问怎么得到'../Embeds/sdp_correct_embeds.pkl'文件？

这个文件就是词向量的文件，不过我们用pickle dump了一下得到了pkl文件，加载的词向量是一个元祖，包括一个vocab和一个numpy array。
词向量的具体格式参考这个代码：https://gist.github.com/LiangsLi/5b01a4611ced34ed957504235b29ee42
我们使用的是腾讯开源的词向量文件
抱歉回复晚了～

**Comment by changsha2999** [comment]
I tried, it seems work:

def dumpx():
	##-download 45000-small.txt: https://github.com/cliuxinxin/TX-WORD2VEC-SMALL
	with open('45000-small.txt') as f: text = f.readlines()
	word_list = [ line.strip().split()[0] for line in text if len(line.strip().split())==201 ]
	Matrix = [ [float(x) for x in line.strip().split()[1:]] for line in text if len(line.strip().split())==201 ]
	emb_list = np.array(Matrix)
	with open("sdp_correct_embeds.pkl", 'wb')as f: pickle.dump((word_list,  emb_list), f)
