### ISSUE TITLE
请问下self.args['nlpcc']指的是什么情况？

### ISSUE THREAD

**Issue by erichuazhou** [LiangsLi/LSTM_Biaffine_Dependency_Parser_PyTorch#2]
请问下self.args['nlpcc']指的是什么情况？谢谢。

**Comment by erichuazhou** [comment]
@LiangsLi

**Comment by LiangsLi** [comment]
@erichuazhou 这个参数控制是否启用NLPCC2019提出的级联解码，就是将两个Biaffine级联在一起，具体实现很简单，[论文](https://github.com/LiangsLi/LSTM_Biaffine_Dependency_Parser_PyTorch/blob/master/Dependency-Gated%20Cascade%20Biaffine%20Network%20for%20CSDG%20Parsing.pdf)
