### ISSUE TITLE
请教下：训练的时候如何处理head=0, deprel=root的情况？为什么dev时出现deprel=<EMPTY>

### ISSUE THREAD

**Issue by erichuazhou** [LiangsLi/LSTM_Biaffine_Dependency_Parser_PyTorch#3]
请教下：
1、训练的时候如何处理head=0, deprel=root的情况？
2、我的dev结果中出现了很多deprel=<EMPTY>的结果，这是怎么回事？
谢谢。
@LiangsLi

**Comment by LiangsLi** [comment]
@erichuazhou Root依存弧是可以正常预测的，代码里已经做了处理，输入的时候会自动在句子前面追加ROOT表示，[代码](https://github.com/LiangsLi/LSTM_Biaffine_Dependency_Parser_PyTorch/blob/d8b2223eb9d388e15543b4f592376774f1114e17/data/sdp_data_loader.py#L114)，由于“Root” deprel本身就在训练数据里，所以也能正常预测

**Comment by LiangsLi** [comment]
@erichuazhou 正常训练的话是不会出现很多</EMPTY/>的，我之前训练的时候也没有出现你这种情况。这个项目的代码后面改了很多，而且结构不是很清晰，可读性比较差，现在我们已经换到新的项目了，[NLPInBLCU/BiaffineDependencyParsing: BERT+Self-attention Encoder ; Biaffine Decoder ; Pytorch Implement](https://github.com/NLPInBLCU/BiaffineDependencyParsing)（虽然重构了，但是项目质量可能还不是很高），如果感兴趣的话可以参考一下，最近我们会再修改一次。

**Comment by LiangsLi** [comment]
@erichuazhou 目前新的项目仅支持BERT一类的预训练模型作为encoder，后续有时间的话我们会支持LSTM等传统模型
